Phlank/low-pressure-zone

src/client/src/api/audiences/audienceResponse.ts
src/client/src/api/audiences/audiences.ts
src/client/src/api/performers/performerResponse.ts
src/client/src/assets/main.scss
src/client/src/assets/primevue-overrides.scss
src/client/src/components/form/requestForms/AudienceForm.vue
src/client/src/components/form/requestForms/PerformerForm.vue
src/client/src/components/form/requestForms/ScheduleForm.vue
src/client/src/components/layout/SiteHeader.vue
src/client/src/components/layout/SiteLayout.vue
src/client/src/components/views/dashboard/DashboardAudiencesView.vue
src/client/src/components/views/dashboard/DashboardPerformersView.vue
src/client/src/components/views/dashboard/DashboardSchedulesView.vue
src/client/src/validation/rules/composed/audienceValidators.ts
src/client/src/validation/rules/composed/scheduleValidators.ts
src/server/LowPressureZone.Api/Endpoints/Audiences/AudienceRequest.Mapper.cs
src/server/LowPressureZone.Api/Endpoints/Audiences/AudienceResponse.cs
src/server/LowPressureZone.Api/Endpoints/Audiences/DeleteAudience.cs
src/server/LowPressureZone.Api/Endpoints/Audiences/GetAudienceById.cs
src/server/LowPressureZone.Api/Endpoints/Audiences/GetAudiences.cs
src/server/LowPressureZone.Api/Endpoints/Performers/GetPerformerById.cs
src/server/LowPressureZone.Api/Endpoints/Performers/GetPerformers.cs
src/server/LowPressureZone.Api/Endpoints/Performers/PerformerResponse.cs
src/server/LowPressureZone.Api/Endpoints/Schedules/GetSchedules.cs
src/server/LowPressureZone.Domain/Entities/Audience.cs

#9 audiences dashboard

---

src/client/src/components/form/ValidationLabel.vue
src/client/src/components/form/requestForms/TimeslotForm.vue
src/client/src/components/views/dashboard/DashboardAudiencesView.vue
src/client/src/components/views/dashboard/DashboardPerformersView.vue
src/client/src/components/views/dashboard/schedules/DashboardSchedulesTimeslotsTable.vue
src/client/src/components/views/dashboard/schedules/DashboardSchedulesView.vue

#32 create edit timeslot in dialog

---

src/client/src/api/apiResponse.ts
src/client/src/assets/styles/layouts.scss
src/client/src/assets/styles/variables.scss
src/client/src/components/data/UpcomingSchedules.vue
src/client/src/components/form/requestForms/TimeslotForm.vue
src/client/src/components/layout/SiteHeader.vue
src/client/src/components/views/HomeView.vue
src/client/src/components/views/dashboard/schedules/DashboardSchedulesTimeslotsTable.vue
src/client/src/components/views/dashboard/schedules/DashboardSchedulesView.vue
src/client/src/utils/dateUtils.ts
src/server/LowPressureZone.Api/Program.cs

#33 front page schedule

---

src/client/src/validation/requestRules.ts

#44 Remove unnecessary escape chars

---

src/client/src/components/views/dashboard/communities/CommunitiesGrid.vue
src/client/src/components/views/dashboard/communities/DashboardCommunitiesView.vue

#80 Update loaded audiences whenever making changes to data

---

src/client/src/App.vue
src/client/src/assets/styles/_layouts.scss
src/client/src/components/form/FormArea.vue
src/client/src/components/views/dashboard/communities/CommunityRelationshipsGrid.vue
src/client/src/components/views/user/LoginView.vue
src/client/src/components/views/user/TwoFactorView.vue
src/client/src/constants/size.ts

#86 Fix width of message for centered panels

---

src/client/src/components/views/dashboard/users/InviteUser.vue

#87 Clear roles, fix issue where organizers could use any community in invitation

---

src/client/src/components/form/FormField.vue
src/client/src/components/views/user/RegisterView.vue

#71 Add message to register view for password help text

---

src/client/src/components/views/home/UpcomingSchedules.vue
src/server/LowPressureZone.Api/Endpoints/Users/Login/PostLogin.cs

#152 Add url to timeslot data, show link icon

---

src/client/.env
src/client/src/components/controls/SiteNavMenu.vue

Add github to site nav

---

src/server/LowPressureZone.Api/Endpoints/Performers/PerformerRequestValidator.cs
src/server/LowPressureZone.Domain/DataContext.cs
src/server/LowPressureZone.Domain/Migrations/20250429200326_DropPerformerNameUniqueConstraint.Designer.cs
src/server/LowPressureZone.Domain/Migrations/20250429200326_DropPerformerNameUniqueConstraint.cs

Remove Performer unique name constraint

---

.idea/.idea.LowPressureZone/.idea/codeStyles/codeStyleConfig.xml
src/client/.env.development
src/client/.env.production
src/client/src/components/layout/site/SiteLayout.vue
src/client/src/components/views/dashboard/communities/DashboardCommunitiesView.vue
src/client/src/components/views/dashboard/streaming/DashboardStreamingView.vue
src/client/src/components/views/dashboard/streaming/ExternalStreamingDirections.vue
src/client/src/components/views/dashboard/streaming/SoftwareStreamingDirections.vue

Fix links to stream status page

---

src/client/src/assets/main.scss
src/client/src/components/layout/site/SiteHeader.vue
src/client/src/components/views/home/AboutSection.vue
src/client/src/components/views/home/HomeView.vue
src/client/src/components/views/home/UpcomingSchedules.vue

Add animation to read more section opening/closing

---

src/client/src/components/controls/ScheduleNavigator.vue
src/client/src/components/form/FormField.vue
src/client/src/components/views/home/UpcomingSchedules.vue

Add navigator for schedules on homepage

---

src/client/src/components/views/dashboard/DashboardView.vue

Update nav text

---

src/client/src/components/controls/PlayButton.vue
src/client/src/components/layout/site/SiteLayout.vue

Add volume slider, fix text oscillation

---

src/client/src/api/resources/streamApi.ts
src/client/src/components/controls/PlayButton.vue
src/client/src/stores/streamStore.ts

Update page title to match stream when playing

---

src/client/src/components/controls/SiteNavMenu.vue
src/client/src/components/layout/site/SiteHeader.vue

Display chat button until 240px

---

src/client/src/components/controls/PlayButton.vue

Fix bg of volume slider on light mode

---

src/client/src/components/views/dashboard/users/InviteUser.vue

Remove key listener from invite form

---

README.md
src/server/LowPressureZone.Api/Rules/TimeslotRules.cs
src/server/LowPressureZone.Api/Services/EmailService.cs
src/server/LowPressureZone.Api/Services/Stream/AzuraCastStreamStatusService.cs
src/server/LowPressureZone.Api/Services/Stream/IcecastStatusService.cs

Allow deletion of timeslots if admin

---

LowPressureZone.sln.DotSettings
src/client/src/api/resources/usersApi.ts
src/client/src/components/dialogs/ConfirmDialog.vue
src/client/src/components/views/dashboard/users/ActiveTab.vue
src/client/src/components/views/dashboard/users/DashboardUsersView.vue
src/client/src/components/views/dashboard/users/UsersGrid.vue
src/server/LowPressureZone.Api/Clients/AzuraCastClient.cs
src/server/LowPressureZone.Api/Endpoints/Users/GetUsers.cs
src/server/LowPressureZone.Api/Endpoints/Users/Streamers/PostStreamers.cs
src/server/LowPressureZone.Api/Endpoints/Users/UserResponse.cs
src/server/LowPressureZone.Api/Extensions/UserManagerExtensions.cs
src/server/LowPressureZone.Api/Models/Result.cs

Add streamers based on site users

---

LowPressureZone.sln.DotSettings
src/client/src/components/form/requestForms/BroadcastingForm.vue
src/client/src/components/views/dashboard/streaming/ExternalStreamingDirections.vue
src/client/src/components/views/dashboard/streaming/LiveConnectionInformation.vue
src/client/src/components/views/dashboard/streaming/SoftwareStreamingDirections.vue
src/client/src/components/views/dashboard/streaming/StreamInformation.vue
src/client/src/components/views/dashboard/streaming/TestConnectionInformation.vue

Update streaming documentation

---

src/client/src/components/controls/PlayButton.vue
src/client/src/components/views/dashboard/streaming/LiveConnectionInformation.vue
src/client/src/components/views/dashboard/streaming/TestConnectionInformation.vue

Try to reconnect audio stream on disconnect

---

src/client/src/components/layout/site/SiteLayout.vue

Fix footer blocking other mouse clicks on page
